db:
  development:
    adapter:  mysql2
    host:     localhost
    encoding: utf8
    username: root
    password: root
    database: nippou_bot_ruby
    pool: 5
  produciton:
    adapter:  pg
    host:     localhost
    encoding: utf8
    username: root
    password:
    database: nippou_bot_ruby
    pool: 5
