db:
  development:
    adapter:  mysql2
    host:     localhost
    encoding: utf8
    username: root
    password: root
    database: nippou_bot_ruby
    pool: 5
  production:
    adapter:  postgresql
    encoding: unicode
    database: nippou_bot_ruby
    pool: 5
    host: /var/run/postgresql
